export const TIMERINTERVAL = "TIMERINTERVAL";
export const BACKWARDINTERVAL = "BACKWARDINTERVAL";
export const TICK = "TICK";
export const START_TIMER = "START_TIMER";
export const STOP_TIMER = "STOP_TIMER";
export const TIMER_STARTED = "TIMER_STARTED";
export const TIMER_STOPPED = "TIMER_STOPPED";
